### ISSUE TITLE
pfamseq.txt

### ISSUE THREAD

**Issue by jnkoberstein** [reynoldsk/pySCA#1]
The ftp url provided for downloading pfamseq.txt (ftp://ftp.sanger.ac.uk/pub/databases/Pfam/current_release/database_files/) is not active. It would be helpful to know which release of pfamseq was used when writing the code for annotate MSA.py, as the current release does not seem to work.

**Comment by reynoldsk** [comment]
I've updated the github pages install instructions to have the new link: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/database_files/, and updated the annotation script to work with the current release. let me know if this doesn't fix things for you
