### ISSUE TITLE
scaSectorID.py issue with kpos

### ISSUE THREAD

**Issue by girodat** [reynoldsk/pySCA#5]
I have been having an issue with the scaSectors.py tool. When I input the command: 
./scaSectorID.py ./PF00028.db 
I received the error 
Selected kpos=4 significant eigenmodes. 
Traceback (most recent call last):
    File "./scaSectorID.py", line 70, in <module>
        ics,icsize,sortedpos,cutoff,scaled_pd, pd = sca.icList(Vpica,kpos,Csca, p_cut=options.cutoff)
    File "/home/dylan/pySca-master/scaTools.py", line 998, in icList
        h_params = np.histogram(Vpica[:,k], nbins)
    File "/home/dylan/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 719, in histogram
         '`bins` must be an integer, a string, or an array')
TypeError: `bins` must be an integer, a string, or an array

I was wondering if anyone had insight into this error?

**Comment by reynoldsk** [comment]
yes... there is a bug here where the 'bins' argument being passed to np.histogram should be cast to an int. Just corrected this in the latest commit - should fix your issue.
